### ISSUE TITLE
"certificate has expired" error shows up after inputing OTP

### ISSUE THREAD

**Issue by fajarism** [human-internet/humanid-reactnative-sdk#6]
Dear Human Internet Team

We faced an error with popup that said "certificate has expired".
This occured both on our development and production environment.

For your information we are using humanid-reactnative-sdk.

Here are the steps to reproduce:
1. Open humanid login webview using the sdk.
2. Input country code and phone number.
3. Input OTP.
4. Error occurs.

Any help is appreciated.
Thanks and best regards.

![Screenshot_2023-07-04-14-44-39-423_org bettersocial dev](https://github.com/human-internet/humanid-reactnative-sdk/assets/55779793/f13e52ab-68bf-4296-a88a-74ab48c3b57d)

**Comment by kofimokome** [comment]
This issue appears to have already been fixed. Will be closing the issue. Feel free to reopen if you still have the issue
