### ISSUE TITLE
Improve Copy-from-SMS + Paste Code in React Native iOS

### ISSUE THREAD

**Issue by tech-lead-humanID** [human-internet/humanid-reactnative-sdk#7]
Should work like Signal:
After phone number is added:
1) Code is copied automatically 'From Messages' and suggested
![Image](https://user-images.githubusercontent.com/46710651/224916157-5bb71602-f561-4aee-a6e2-751384be32bf.png)

2) After clicking, code is pasted correctly (right now: only first number is pasted)
![Image](https://user-images.githubusercontent.com/46710651/224916311-6834b6ec-d2a0-4a10-9f27-53635756eda1.png)

**Comment by tech-lead-humanID** [comment]
@kofimokome Should this project fall under react native SDK repo? Just wanted to categorize/tag it

**Comment by kofimokome** [comment]
I think so. Looks more like a web login issue than a React native issue.
We can leave it here

**Comment by ccrawford4** [comment]
@kofimokome Looks like "copy from messages" works correctly for humanId login on the Helio native iOS app. May I close this issue?
